PRACTICA:
-- 1-Crear la tabla MATERIA  especificando restricciones de clave 
-- primaria, y clave for�nea si es posible. 
-- El campo COD_MATERIA debe ser �nico y secuencial con incremento 1. 
CREATE TABLE MATERIA (
COD_MATERIA INT IDENTITY(1,1) NOT NULL,
NOMBRE_MATERIA VARCHAR (20) NOT NULL,
COD_CARRERA INT NOT NULL,

CONSTRAINT PK_MATERIA PRIMARY KEY (COD_MATERIA)
--CONSTRAINT FK_MATERIA_CARRERA 
)

-- 2-Crear la tabla CARRERA. 
-- Especificar con una restricci�n que el campo NOMBRE_CARRERA debe ser �nico. 
-- S�lo el campo fecha de cierre de inscripci�n permite nulos. 
CREATE TABLE CARRERA (
COD_CARRERA INT IDENTITY (1,1) NOT NULL,
NOMBRE_CARRERA VARCHAR (40) NOT NULL,
DURACION_CARRERA INT NOT NULL,
FECHA_CIERRE_INSC_CARRERA DATE NULL,

CONSTRAINT PK_CARRERA PRIMARY KEY (COD_CARRERA),
CONSTRAINT U_NOMBRE_CARRERA UNIQUE (NOMBRE_CARRERA))

-- 3-Agregar la FK correspondiente en la tabla MATERIA.
ALTER TABLE MATERIA
ADD CONSTRAINT FK_MATERIA_CARRERA FOREIGN KEY (COD_CARRERA)
REFERENCES CARRERA (COD_CARRERA)

ALTER TABLE MATERIA
DROP CONSTRAINT FK_MATERIA_CARRERA

-- 4-Agregar la siguiente restricci�n a la tabla CARRERA: la duraci�n de la
--   carrera no pueder ser menor a cero ni mayor que tres.
ALTER TABLE CARRERA
ADD CONSTRAINT CK_DURACION CHECK (DURACION_CARRERA >= 0 AND DURACION_CARRERA <= 3)

-- 6-Insertar al menos tres nuevos registros en las tablas: 
--   CARRERA, y MATERIA
--   Especifique valores de ejemplo.
INSERT INTO CARRERA (NOMBRE_CARRERA, DURACION_CARRERA, FECHA_CIERRE_INSC_CARRERA)
VALUES ('TUP', 2, NULL)
INSERT INTO CARRERA (NOMBRE_CARRERA, DURACION_CARRERA)
VALUES ('TUSI', 3)
INSERT INTO CARRERA (NOMBRE_CARRERA, DURACION_CARRERA, FECHA_CIERRE_INSC_CARRERA)
VALUES ('ISI', 3, NULL)
INSERT INTO CARRERA (NOMBRE_CARRERA, DURACION_CARRERA, FECHA_CIERRE_INSC_CARRERA)
VALUES ('ISI2', 3, '2025-06-09')

SELECT * FROM CARRERA

INSERT INTO MATERIA (NOMBRE_MATERIA, COD_CARRERA)
VALUES ('BDI', 1)
INSERT INTO MATERIA (NOMBRE_MATERIA, COD_CARRERA)
VALUES ('AYSO', 1)
INSERT INTO MATERIA (NOMBRE_MATERIA, COD_CARRERA)
VALUES ('ALG', 5)

SELECT * FROM MATERIA

-- 7-Actualizar el valor del campo DURACION = 2
--   para todos las carreras con c�digo de carrera (1,3) 

-- 5-Crear la tabla MATERIA_CORRELATIVA con la FK respectiva.
